version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: finbridge_postgres
    environment:
      POSTGRES_USER: finbridge
      POSTGRES_PASSWORD: finbridge_dev_password
      POSTGRES_DB: finbridge_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: finbridge_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  adminer:
    image: adminer
    container_name: finbridge_adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
